version: "3.9"
services:
  neo4j:
    image: "neo4j:3.5.2"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
  keycloakdb:
    image: postgres:11
    ports:
        - "5406:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=keycloak
    volumes:
        - ./keycloak-data:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak
    ports:
        - "8090:8080"
    links:
        - keycloakdb
    depends_on:
        - keycloakdb
    environment:
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        - DB_USER=postgres
        - DB_PASSWORD=postgres
        - DB_VENDOR=postgres
        - DB_ADDR=keycloakdb
        - DB_PORT=5432
        - JDBC_PARAMS='useSSL=false'
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    environment:
      - NODE_ENV=development
   